import React from "react";
import { redirect } from "next/navigation";
import { createClient } from "@/utils/supabase/server";
import { LayoutDashboard, Calendar, Code, Settings, Bell, Search, FileCode2 } from "lucide-react";
import Link from "next/link";
import { SidebarLink } from "@/components/dashboard/sidebar-link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { UserNav } from "@/components/dashboard/user-nav";
import { ThemeToggle } from "@/components/theme-toggle";
import { CommandMenu } from "@/components/dashboard/command-menu";
import { DynamicBreadcrumbs } from "@/components/dashboard/dynamic-breadcrumbs";
import { InteractiveNotifications } from "@/components/dashboard/interactive-notifications";
import { BrandLogo } from "@/components/ui/brand-logo";

export default async function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();

  console.log(`[Dashboard Layout] SSR User retrieved:`, user?.id);

  if (!user) {
    console.log(`[Dashboard Layout] No user found, redirecting to /login`);
    redirect("/login");
  }

  const role = user.user_metadata?.role || "candidate";
  
  // Custom tailored navigation links dynamically generated by authenticated role
  const navLinks = role === 'candidate' ? [
    { href: `/dashboard/candidate`, label: "Overview", icon: LayoutDashboard },
    { href: `/dashboard/candidate/interviews`, label: "My Interviews", icon: Calendar },
    { href: `/dashboard/candidate/practice`, label: "Practice Playground", icon: Code },
    { href: `/dashboard/candidate/submissions`, label: "Submissions History", icon: FileCode2 },
    { href: `/dashboard/candidate/settings`, label: "System Preferences", icon: Settings },
  ] : role === 'interviewer' ? [
    { href: `/dashboard/interviewer`, label: "Overview", icon: LayoutDashboard },
    { href: `/dashboard/interviewer/interviews`, label: "Schedule Round", icon: Calendar },
    { href: `/dashboard/interviewer/settings`, label: "System Preferences", icon: Settings },
  ] : [
    { href: `/dashboard/admin`, label: "Console Overview", icon: LayoutDashboard },
    { href: `/dashboard/admin/interviews`, label: "Manage Interviews", icon: Calendar },
    { href: `/dashboard/admin/settings`, label: "System Preferences", icon: Settings },
  ];

  return (
    <div className="flex min-h-screen bg-background dark:bg-zinc-950 font-sans selection:bg-primary/20">
      {/* Sidebar - Minimal premium glassmorphic sidebar */}
      <aside className="hidden md:flex w-[260px] flex-col border-r bg-card/40 backdrop-blur-xl">
        <div className="h-14 flex items-center px-6 border-b border-border/50">
          <Link href={`/dashboard/${role}`} className="flex items-center gap-2.5 group">
            <BrandLogo size="md" className="w-8 h-8 bg-primary/10 rounded-lg p-1 flex items-center justify-center group-hover:bg-primary/20 transition-all duration-300 shadow-md shadow-primary/5" />
            <span className="font-semibold text-lg tracking-tight bg-gradient-to-r from-foreground via-foreground to-foreground/80 bg-clip-text">InterviewAI</span>
          </Link>
        </div>
        
        <div className="px-4 py-4">
          <CommandMenu role={role} />
        </div>
 
        <nav className="flex-1 overflow-y-auto py-2 px-3 space-y-1">
          {navLinks.map((link) => (
            <SidebarLink
              key={link.href}
              href={link.href}
              className="flex items-center gap-3 px-3 py-2 rounded-md text-sm font-medium transition-all duration-250 group"
            >
              <link.icon className="w-4.5 h-4.5 transition-colors" />
              {link.label}
            </SidebarLink>
          ))}
        </nav>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col h-screen overflow-hidden relative">
        {/* Premium Background Gradients */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-purple-500/5 rounded-full blur-[100px] -z-10 pointer-events-none mix-blend-screen dark:mix-blend-lighten"></div>
        <div className="absolute bottom-0 left-0 w-[500px] h-[500px] bg-blue-500/5 rounded-full blur-[100px] -z-10 pointer-events-none mix-blend-screen dark:mix-blend-lighten"></div>

        {/* Topbar */}
        <header className="h-14 flex items-center justify-between px-4 md:px-8 border-b border-border/50 bg-card/40 backdrop-blur-xl z-20 sticky top-0">
          <div className="flex items-center gap-4">
            {/* Mobile branding */}
            <Link href={`/dashboard/${role}`} className="md:hidden flex items-center gap-2">
              <BrandLogo size="md" className="w-8 h-8 bg-primary/10 rounded-lg p-1 flex items-center justify-center shadow-md shadow-primary/5" />
            </Link>

            <DynamicBreadcrumbs role={role} />
          </div>

          <div className="flex items-center gap-3">
            <InteractiveNotifications role={role} />
            <ThemeToggle />
            <div className="h-4 w-px bg-border mx-1 hidden md:block" />
            <UserNav user={user} role={role} />
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-4 md:p-8 z-10 scroll-smooth">
          <div className="max-w-7xl mx-auto">
            {children}
          </div>
        </div>
      </main>
    </div>
  );
}
